# Generated by Django 2.2.13 on 2021-02-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210210_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='testProduct'),
            preserve_default=False,
        ),
    ]
