# Generated by Django 2.2.13 on 2021-02-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='users',
            new_name='user',
        ),
    ]
