# Generated by Django 2.2.13 on 2021-02-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
    ]
