# Generated by Django 2.2.13 on 2021-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210214_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='item',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='core.Item'),
        ),
    ]
