# Generated by Django 2.2.13 on 2021-02-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210214_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='item',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
    ]
