# Generated by Django 2.2.13 on 2021-02-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210214_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhishList',
        ),
    ]
