# Generated by Django 2.2.13 on 2021-02-14 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_item_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='item',
            name='wishlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
