# Generated by Django 2.2.13 on 2021-02-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
